### ISSUE TITLE
can crictl load or save images like docker or containerd?

### ISSUE THREAD

**Issue by oldthreefeng** [kubernetes-sigs/cri-tools#707] opened 2020-12-14 14:54 UTC
#### What would you like to be added:

like docker or containerd,  the command is 
```
# docker
docker save -o xxx.tar $imageList
docker load -i  xxx.tar
# containerd
ctr -n=k8s.io image export  xxx.tar  $imageList
ctr -n=k8s.io image import  xxx.tar
```

#### Why is this needed:
for crictl.  its better to support who likes to use docker/containerd  when kubernetes 1.22 come

**Comment by jwstein3400** [comment] 2021-02-26 05:04
Duplicate of #546

**Comment by saschagrunert** [comment] 2021-03-01 09:16
@oldthreefeng thank you for the request! Unfortunately image loading is not part of the Container Runtime Interface (CRI), which is the main interface for crictl. Therefore we will not have a chance to implement it right now.

/close

**Closed by saschagrunert** 2021-03-01 09:16 UTC
Labels: kind/feature, sig/node
