### ISSUE TITLE
`crictl --version` reports unknown

### ISSUE THREAD

**Issue by andriyDev** [kubernetes-sigs/cri-tools#798] opened 2021-07-20 22:44 UTC
Running on Debian 5.10.40-1rodete2, `crictl --version` reports unknown. This seems to be something about the linking flags not populating the version.

**Comment by saschagrunert** [comment] 2021-07-21 07:15
Hey @andriyDev, how did you build or install crictl?

**Comment by andriyDev** [comment] 2021-07-21 16:34
We are building a docker image from `ubuntu:focal-20210401` (`ubuntu 20.04`), and just installing through apt-get. No version is specified, although we seem to be using https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ as a repo source.

Context: https://github.com/andriyDev/minikube/blob/0e74c3d4fedbf0ba046e66054f62a5a91ab611df/deploy/kicbase/Dockerfile?plain=1#L140

**Comment by saschagrunert** [comment] 2021-07-22 08:48
Yeah this looks like an issue with how the package builds the binary, let me check if we can fix it.

**Comment by saschagrunert** [comment] 2021-07-22 09:46
Proposed a fix in https://build.opensuse.org/request/show/907694

**Comment by saschagrunert** [comment] 2021-07-22 10:40
Should be fixed now for all OBS packages :)

**Closed by saschagrunert** 2021-07-22 10:40 UTC
Labels: kind/bug, sig/node

**Comment by afbjorklund** [comment] 2021-08-05 08:12
Confirmed fixed in 1.21.0~2
