### ISSUE TITLE
1.16 regressed creating pod from local images

### ISSUE THREAD

**Issue by cgwalters** [kubernetes-sigs/cri-tools#548] opened 2019-10-10 19:03 UTC
Sorry for the vague bug report, but we have [crio tests](https://github.com/coreos/mantle/blob/d15c8c761aff1ae628136ca6a853c0d9e07282cf/kola/tests/crio/crio.go) in our CoreOS tests (used for RHEL CoreOS) that recently started failing when cri-tools was bumped 1.14 :arrow_right:  1.16.

```
--- FAIL: crio.base (92.16s)
    --- PASS: crio.base/crio-info (0.36s)
    --- FAIL: crio.base/networks-reliably (12.31s)
            cluster.go:122: STEP 1: FROM scratch
            cluster.go:122: STEP 2: COPY . /
            cluster.go:122: STEP 3: COMMIT localhost/ping
            cluster.go:122: Getting image source signatures
            cluster.go:122: Copying blob sha256:279dd629a2dbaa7738f75077cfdfc8644bcbd824261888ce8a400bdff237fe70
            cluster.go:122: Copying config sha256:5b50d4e85a9e65cf35633145899e7bd28f091907fc5874a0b668ac3af6a6ca96
            cluster.go:122: Writing manifest to image destination
            cluster.go:122: Storing signatures
            cluster.go:122: time="2019-10-10T13:27:56Z" level=fatal msg="Creating container failed: rpc error: code = Unknown desc = pinging docker registry returned: Get http://localhost/v2/: dial tcp [::1]:80: connect: connection refused"
            cluster.go:139: "sudo crictl create d72fa817837e8db8236c16afce8a65f4037ba07e115c12b2e56e6933e35d0919 pingContainer629525586 ping1Pod216712447" failed: output , status Process exited with status 1
```

I only briefly debugged this but basically we're building images locally into the containers/image store, so they end up named `localhost/`.  I think cri-tools in 1.16 is trying to "resolve" that name.

**Comment by saschagrunert** [comment] 2019-10-24 18:14
Hey, @cgwalters, is this issue now resolved or ist there any open bug which can be resolved here?

**Comment by haircommander** [comment] 2019-10-25 18:24
@cgwalters I ran into a similar issue upgrading the CI for cri-o. Does adding the option `--no-pull` to the create command fix it for you?

**Comment by ashcrow** [comment] 2020-01-15 15:39
We're still seeing this issue as of today.

**Comment by miabbott** [comment] 2020-01-15 15:40
@haircommander I ran into this recently working on the RHCOS compose; if I add `--no-pull` to our tests, it causes them to pass again.

Still troubles me that the CLI behavior of `crictl create` in this case broke between 1.14 and 1.16

**Comment by saschagrunert** [comment] 2020-01-17 11:55
> @haircommander I ran into this recently working on the RHCOS compose; if I add `--no-pull` to our tests, it causes them to pass again.
> 
> Still troubles me that the CLI behavior of `crictl create` in this case broke between 1.14 and 1.16
> 
> Will this use case get fixed or should we require `--no-pull` in our tests?

Hey @miabbott, this is not a general regression but was more an intended behavior change. Is there anything we can do to support you here or are you fine with the `--no-pull` flag?

**Comment by ashcrow** [comment] 2020-01-17 14:21
We can make the `--no-pull` flag work, but it did break backwards compatibility for those using `ctictl`. We utilize it as part of our [kola testing](https://github.com/coreos/mantle/blob/master/kola/tests/crio/crio.go). Because of the change in usage it was assumed there was some kind of regression or bug in `crictl` and kept us from promoting it.

We've since learned of `--no-pull` and updated the testing so we will hopefully be able to verify all is well for future use.

**Comment by miabbott** [comment] 2020-01-21 14:23
> Hey @miabbott, this is not a general regression but was more an intended behavior change. Is there anything we can do to support you here or are you fine with the `--no-pull` flag?

As @ashcrow noted, we've updated our tests to use `--no-pull` (coreos/mantle#1116), so all is well.  :)

**Comment by saschagrunert** [comment] 2020-01-21 14:25
Alright, I will close this issue now but feel free to reopen in case of any further errors. :)

**Closed by saschagrunert** 2020-01-21 14:25 UTC
